### ISSUE TITLE
DevOps for the -component repository.

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-components#480]
## Description
Templates and packages (C# and JS) need an automated publishing pipeline to reduce friction for component developers.

## Work items
- [x] Pipeline steps
  - [x] dotnetBuildSteps - _Run `dotnet build`_
  - [x] dotnetPackSteps - _Run `dotnet pack`_
  - [x] dotnetPushSteps - _Run `dotnet push`_
  - [x] dotnetRestoreSteps - _Run `dotnet restore`_
  - [x] npmPublishSteps - _Run `npm publish`_
  - [x] nugetPackSteps - _Run `nuget pack` (for .nuspec)_
  - [x] nugetPushSteps - _Run `nuget push` (for .nuspec)_
  - [x] useDotnetSteps - _Use dotnet 2.x/3.x_
  - [x] codeSignSteps - _Sign nuget packages_
  - [x] versionTaggingSteps - _Add version tag based on deployment ring and branch_ 
  - [x] publishBuildArtifactsSteps - _Publish files to build aritfacts_
  - [x] debugSteps - Display environment variables and workspace_
- [x] Determine permissions to publish to nuget.org/npm GA
- [x] Determine Azure Artifacts feed and views for preview packages
- [x] Transition to SDK_v4 pipelines
 
### componentPipelineTemplate
_User can create a new template extending the componentPipelienTemplate, specifying a component type that calls related subtemplate._
#### Parameters
```
name: componentType
  displayName: 'What is the component type? Determines deployment steps.'
  type: string
  values:
  - declarativeAsset
  - plugin
  - generator

name: deploymentRing
  displayName: 'What is the component type? Determines deployment steps.'
  type: string
  default: privatePreview
  values:
  - privatePreview
  - publicPreview
``` 

### declarativeAssetPipelineStages
Declarative assets are published to both NuGet and NPM. This assumes they already include .nuspec and package.json files, respectively. Uses `nuget` rather than `dotnet` commands due to supportability of .nuspec file.

- Validate that required packaging files are provided. 
- Run `nuget pack`  
- Sign with the ESRP CodeSign task. 
- Publish .nupkg to build artifacts. 
- Publish node package to build artifacts. 

### generatorPipelineStages
Template generators are published to NPM. This assumes they already include a package.json file.

- Publish node packages to build artifacts. 

### pluginPipelineStages
Plugins are published to NuGet and/or NPM depending on their source languages. There will be conditional checks in the subtemplate for language specific steps.

- Use .Net Core 2.x/3.x. 
- Use packages appropriate to ring: daily builds use latest daily SDK, regular use latest release SDK 
- Run `dotnet restore` 
- Run `dotnet build` 
- Run `dotnet pack` 
- Sign with the ESRP CodeSign task. 
- Publish binaries and .nupkg to build artifacts. 

## Notes
* Since there will be many components with many different versions, versioning will be manually set in source control and updated when necessary
* Avoid publishing to NuGet until we have the publishing cadence working smoothly, we should start with MyGet to revert/overwrite versions if necessary.
* Follow up on package unit testing (delegating to Skills crew who have more complex packages)
* Follow up with vNext integration testing (run generator, dialog merge cmd, etc.)

**Comment by ryanlengel** [comment]
Migration is completed
