### ISSUE TITLE
Refactor -components repo

### ISSUE THREAD

**Issue by ryanlengel** [microsoft/botframework-components#520]
# Roadmap
- [x] **Adaptive Bot Generator**
  - [x] Setup
    - [x] Move /experimental/generator-adaptive-bot -> /generators/generator-adaptive-bot
  - [x] Pipelines
    - [x] Add /build/yaml/generators/generator-adaptive-bot.yml template
    - [x] Setup related pipelines in ADO with preview status config
- [x] **Calendar**
  - [x] Setup
    - [x] Merge onto main (PRs: #529, #530)
    - [x] Move calendar-related components
      - [x] Move /experimental/packages/msgraph -> /packages/msgraph
      - [x] Add packages for calendar actions at /packages/calendar
dependencies on above plugins
   - [x] Pipelines
     - [x] Add /build/yaml/plugins/calendar.yml template to preview/calendar
     - [x] Add /build/yaml/plugins/msgraph.yml template to preview/calendar
     - [x] Setup related pipelines in ADO with preview status config
  - [x] Prepare for R12
    - [x] Rename to Microsoft.Bot.Component.* namespace
    - [x] Set versions appropriate to preview status
- [x] **Conversational Core**
  - [x] Setup
    - [x] Merge onto main
    - [x] Move conversational core related components
      - [x] Move /experimental/packages/welcome -> /packages/welcome
      - [x] Move /experimental/packages/helpandcancel -> /packages/helpandcancel
      - [x] Move /experimental/generators/conversational-core -> /generators/generator-conversational-core
      - [x] Deprecate old template at /experimental/packages/conversationalcore
      - [x] Deprecate old components (Greeting, General, UnknownIntent) at /experimental/packages/*
  - [x] Pipelines
    - [x] Add /build/yaml/plugins/welcome.yml template
    - [x] Add /build/yaml/plugins/helpandcancel.yml template to preview/conversational-core
    - [x] Add /build/yaml/generators/generator-conversational-core.yml template to preview/conversational-core
    - [x] Setup related pipelines in ADO with preview status config

# Output
## build/
**Branch**; `main` and subsequent child branches.
_YAML files for Azure DevOps deployment steps.

## generators/
_Includes generators for templates and samples_
### Adaptive bot generator
Generator that instantiates adaptive bot runtime

### Microsoft.Bot.Template.ConversationalCore
**Branch**: `preview/conversational-core`
Template generator for conversational core bot and related packages.

## packages/
_Includes packages for declarative assets (Nuget & NPM). Includes packages for adapters, custom actions, middleware, etc. (NuGet or NPM depending on language)._

### Microsoft.Bot.Component.Welcome
**Branch**: `preview/conversational-core`
Declarative assets for greeting dialog. Published to NuGet & NPM.

### Microsoft.Bot.Component.HelpAndCancel
**Branch**: `preview/conversational-core`
Declarative assets for cancel dialog. Published to NuGet & NPM.

### Microsoft.Bot.Component.Recognizers.Orchestrator
**Branch**: `preview/orchestrator-recognizer`
Plugin for Orchestrator recognizer.

### Microsoft.Bot.Component.Calendar
**Branch**: `preview/calendar`
Plugin for calendar dialogs. Published to NuGet-related feeds.

### Microsoft.Bot.Component.MsGraph
**Branch**: `preview/calendar`
Plugin for msgraph custom actions. Published to NuGet-related feeds.

## skills/
_Waterfall skills from previous work. Not listing them all here but the structure will look the same as it is currently on `main` branch._

## tests/
_Tests for related packages and templates can go here when available.

## tools/
_Scripts and tools to enable development for content across components repo, like the bot template generator generator._
### Bot Template Generator
A tool to help components devs get boilerplate scaffolding when building templates and samples.

**Comment by ryanlengel** [comment]
Existing components have been refactored to the new structure
