### ISSUE TITLE
Generators: Unit test coverage

### ISSUE THREAD

**Issue by peterinnesmsft** [microsoft/botframework-components#665]
### Generated Bot unit test coverage

- [ ] #1076 Core Bot with Language: Unit test coverage
- [ ] #1077 Core Assistant: Unit test coverage

### Generator unit test coverage

- [ ] #1084 Add @microsoft/generator-bot-adaptive unit test coverage
- [ ] #1085 Add @microsoft/generator-bot-core-assistant unit test coverage
- [ ] #1086 Add @microsoft/generator-bot-core-language unit test coverage
- [ ] #1087 Add @microsoft/generator-bot-empty unit test coverage
- [ ] #1088 Add @microsoft/generator-bot-enterprise-assistant unit test coverage
- [ ] #1089 Add @microsoft/generator-bot-enterprise-calendar unit test coverage
- [ ] #1090 Add @microsoft/generator-bot-enterprise-people unit test coverage

**Comment by peterinnesmsft** [comment]
@ryanlengel thanks for creating the other two issues related to this! I had actually intended for unit tests for the generators themselves, but I think this actually calls out a good distinction that in addition to unit testing the generators and their functionality, we also need some level of test coverage for the generated bots themselves.

I'll update the issue description to link to additional issues I've created to track generator unit test coverage so that they are tracked explicitly. Let's sync on your thoughts around testing the generated bots themselves.
